### PR TITLE
Support for PostgreSQL version 13 and 14

### PR DESCRIPTION
**Pull request by SPKorhonen**
This PR contains minimal necessary modifications to bingo which enable support for PostgreSQL versions 13 and 14. If and when merged issue #466 can be closed.

### CODE REVIEW

**Comment by AlexanderSavelyev** [comment]
Hi @SPKorhonen . Much appreciated for the PR. I will run all tests (most probable during NY holidays) for the Bingo to ensure it works correctly and merge

**Comment by SPKorhonen** [comment]
Greetings @AlexanderSavelyev. Good to hear that you will run more extensive tests. If you only test a limited combination of build environments you get "works for me" -code. On that note, please find an additional patch (3d6ef66) to my PR. It prevents problems in linker name resolution as I got bitten by different build environment.

**Comment by AlexanderSavelyev** [comment]
@SPKorhonen  could you please fix the merge conflicts?

**Review by AlexanderSavelyev — APPROVED** [review]
all changes seems reasonable. The error handling will be slightly modified in the PR #593
all unit tests were passed for Linux x86_64 both for 13 and 14 version. Merging the PR

**Comment by SPKorhonen** [comment]
Great work @AlexanderSavelyev! It's good that this issue has been resolved.

FYI: I've been running bingo using PSQL 13 and 14 under Win10 and everything seems to be working.

**Pull request merged**
