### PR TITLE
Indigo build fails (indigo::Exception::Exception() is private within this context)

### PR DESCRIPTION
**Pull request by SunFellow**
Dear Indigo team,
compilation from source fails for me.
Thank you in advance

> export BINGO_PG_DIR=path_to_postgresql_installation

> $BINGO_PG_DIR/bin/psql --version
psql (PostgreSQL) 13.2

> cat /etc/SUSE-brand 
openSUSE
VERSION = 15.3

> uname -a
Linux node8333 5.3.18-55-default #1 SMP Mon Apr 12 13:17:48 UTC 2021 (4897c7e) x86_64 x86_64 x86_64 GNU/Linux

> python -V
Python 3.9.4

> cmake --version
cmake version 3.17.0

> g++ --version
g++ (SUSE Linux) 7.5.0

> java --version
openjdk 11.0.10 2021-01-19

> git clone https://github.com/epam/Indigo.git
> cd Indigo
> python build_scripts/bingo-release.py --preset=linux64 --dbms=postgres
cmake -G "Unix Makefiles" -DSUBSYSTEM_NAME=x64 -DCMAKE_BUILD_TYPE=Release /tmp/Indigo/build_scripts/bingo-postgres
-- System-specific folder name: Linux
-- Subsystem-specific folder name: x64
-- CMAKE_C_FLAGS -include /tmp/Indigo/common/cmake/../hacks/gcc_preinclude.h  -m64
-- CMAKE_CXX_FLAGS -include /tmp/Indigo/common/cmake/../hacks/gcc_preinclude.h  -m64 -std=c++11
-- Common output dir: /tmp/Indigo/build/pg_UnixMakefiles_ReleaseSUBSYSTEM_NAME_x64/dist/Linux/x64
-- Using local ZLib library
-- BingoCore version is 1.9.1.r127
-- CMAKE_C_FLAGS -include /tmp/Indigo/common/cmake/../hacks/gcc_preinclude.h -include /tmp/Indigo/common/cmake/../hacks/gcc_preinclude.h  -m64 -m64
-- CMAKE_CXX_FLAGS -include /tmp/Indigo/common/cmake/../hacks/gcc_preinclude.h -include /tmp/Indigo/common/cmake/../hacks/gcc_preinclude.h  -m64 -std=c++11 -m64 -std=c++11
-- BingoPostgres version is 1.9.1.r127-gc5684e9c linux64
-- Postgres found at /tmp/postgresql/include/server
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/Indigo/build/pg_UnixMakefiles_ReleaseSUBSYSTEM_NAME_x64
...
[ 70%] Building C object inchi/CMakeFiles/inchi.dir/INCHI_BASE/src/ichi_bns.c.o
In file included from /tmp/Indigo/bingo/bingo-core/src/core/bingo_index.h:26:0,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.h:24,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.cpp:19:
/tmp/Indigo/bingo/bingo-core/src/core/bingo_error.h: In constructor ‘BingoError::BingoError(const char*, ...)’:
/tmp/Indigo/bingo/bingo-core/src/core/bingo_error.h:30:5: error: ‘indigo::Exception::Exception()’ is private within this context
     {
     ^
In file included from /tmp/Indigo/common/base_cpp/array.h:29:0,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.h:22,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.cpp:19:
/tmp/Indigo/common/base_cpp/exception.h:34:9: note: declared private here
         Exception() = delete;
         ^~~~~~~~~
In file included from /tmp/Indigo/bingo/bingo-core/src/core/bingo_index.h:26:0,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.h:24,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.cpp:19:
/tmp/Indigo/bingo/bingo-core/src/core/bingo_error.h:30:5: error: use of deleted function ‘indigo::Exception::Exception()’
     {
     ^
In file included from /tmp/Indigo/common/base_cpp/array.h:29:0,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.h:22,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.cpp:19:
/tmp/Indigo/common/base_cpp/exception.h:34:9: note: declared here
         Exception() = delete;
         ^~~~~~~~~
In file included from /tmp/Indigo/bingo/bingo-core/src/core/bingo_index.h:26:0,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.h:24,
                 from /tmp/Indigo/bingo/bingo-core/src/core/mango_index.cpp:19:
/tmp/Indigo/bingo/bingo-core/src/core/bingo_error.h:34:9: error: ‘_init’ was not declared in this scope
         _init("core", format, args);
         ^~~~~
/tmp/Indigo/bingo/bingo-core/src/core/bingo_error.h:34:9: note: suggested alternative: ‘uint’
         _init("core", format, args);
         ^~~~~
         uint
etc...

### CODE REVIEW

**Comment by SunFellow** [comment]
@byte-for-byte,
Thank you for reporting!
We are sorry about this bug; we missed Bingo from our attention.
Can you please pull and check out the branch bugfix/400 and test if it solves your problem? The branch is currently just 1 commit ahead of master.
Thank you.

**Comment by byte-for-byte** [comment]
Dear SunFellow,
thanks for the patch. we are getting closer but a bit is still missing! :)

[ 90%] Building CXX object bingo-core-c/CMakeFiles/bingo-core-c.dir/src/ringo_core_c_parallel.cpp.o
/home/chris/fz/git_clones/theokindb/software/Indigo/bingo/bingo-core-c/src/bingo_core_c_parallel.cpp: In member function ‘virtual void indigo::bingo_core::IndexingCommand::execute(indigo::OsCommandResult&)’:
/home/chris/fz/git_clones/theokindb/software/Indigo/bingo/bingo-core-c/src/bingo_core_c_parallel.cpp:186:15: error: ‘class indigo::Exception’ has no member named ‘throwSelf’
             e.throwSelf();
               ^~~~~~~~~
gmake[2]: *** [bingo-core-c/CMakeFiles/bingo-core-c.dir/build.make:93: bingo-core-c/CMakeFiles/bingo-core-c.dir/src/bingo_core_c_parallel.cpp.o] Error 1

**Comment by mkviatkovskii** [comment]
Dear @byte-for-byte,
We are working on final fix for your issue, hope to provide it very soon.

**Comment by mkviatkovskii** [comment]
Dear @byte-for-byte,
Could you please take a look at new version in `master` branch? Also let me notify you that build scripts were significantly changed, and now you need to build `bingo-oracle` this way:
```bash
mkdir build
cd build
cmake ..
make -j package-bingo-oracle 
```

**Comment by byte-for-byte** [comment]
Hi,
i am confused now. I was following the instructions in 
https://github.com/ggasoftware/indigo/blob/master/README.md

SunFellow fixed the first compilation error in bugfix/400 which was good progress. Is it possible to address the next error I mention above?

Also, I guess I misunderstand the 'updated' build instruction from the last comment:

git clone --branch master https://github.com/epam/Indigo.git
cd Indigo
mkdir build
cd build
cmake ..
make -j package-bingo-oracle

**make: *** No rule to make target 'package-bingo-oracle'.  Stop.**

Or should I do this in Indigo/bingo/? (which gives the same error).

**Comment by SunFellow** [comment]
Hi @byte-for-byte,

I've added a fix to this branch / pull request. I hope no other debris after `class Exceptions` reduction (unfortunately I cannot check bingo).
Meanwhile the master was radically updated, but you can keep using this branch: it is based on old master.

**Comment by byte-for-byte** [comment]
Hi SunFellow,

sorry for the bad news, but unfortunately, it is still not working:

> git clone --branch bugfix/400 https://github.com/epam/Indigo.git
cd Indigo 
python build_scripts/bingo-release.py --preset=linux64 --dbms=postgres

[ 93%] Building CXX object bingo-postgres/CMakeFiles/bingo-postgres-shared.dir/src/pg_am/pg_mango_utils.cpp.o
In file included from /home/chris/fz/git_clones/theokindb/software/Indigo/bingo/postgres/src/pg_am/pg_bingo_search.cpp:20:0:
/home/chris/fz/git_clones/theokindb/software/Indigo/bingo/postgres/src/pg_common/bingo_pg_common.h: In constructor ‘BingoPgError::BingoPgError(const char*, ...)’:
/home/chris/fz/git_clones/theokindb/software/Indigo/bingo/postgres/src/pg_common/bingo_pg_common.h:463:5: error: ‘indigo::Exception::Exception()’ is private within this context

...loads more...

also:
In file included from /home/chris/fz/git_clones/theokindb/software/Indigo/bingo/postgres/src/pg_am/pg_bingo_import.cpp:20:0:
/home/chris/fz/git_clones/theokindb/software/Indigo/bingo/postgres/src/pg_common/bingo_pg_common.h:435:51: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
         errfinish((errcode(ERRCODE_INTERNAL_ERROR), pg_err_mess));                                                                                             \
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~

**Comment by SunFellow** [comment]
@byte-for-byte ,
It seems you are the first one who compiled C++ bingo :) At least, with -fpermissive flag. So thank you for great contribution.
Please try again.

**Comment by AlexanderSavelyev** [comment]
The issue appears after the recent Exception class change. It seems the #340 PR was merged without testing bingo. Need to add some bingo tests into the github actions to avoid this issues in the future

**Comment by SunFellow** [comment]
@byte-for-byte,
If you are using postres/postrges software at github, please pay attention to this commit:
https://github.com/postgres/postgres/commit/17a28b03645e27d73bf69a95d7569b61e58f06eb
There they seem to break compatibility of declaration of `errfinish()`, that might be the reason of the last error. 
In this case, please change the corresponding usages of postgres imported names by your own. (Otherwise we will fix it for ages).

**Comment by SunFellow** [comment]
@byte-for-byte ,
Please try again. 
What about the error caused by:
`errfinish((errcode(ERRCODE_INTERNAL_ERROR), pg_err_mess));`
I revoked the latest commit. I'm sorry, I cannot help right now: these are external dependencies. 
Try to compile without -fpermissive flag.

**Comment by AlexanderSavelyev** [comment]
in master branch now everything is built using github actions
The binary can be taken from the actions artifacts, e.g. this one
https://github.com/epam/Indigo/actions/runs/774138905

If you want to compile from source please take scripts from the actions file
https://github.com/epam/Indigo/blob/54e24353c5eb6b3690e69bf32cd57f629c0f513b/.github/workflows/indigo-ci.yaml#L569

Please take into account that the current supported version of postgres is 10, 11 and 12

**Comment by AlexanderSavelyev** [comment]
All the issues were fixed in master
I managed to compile using WSL (Ubuntu 20.04)

```
wget -P pg https://ftp.postgresql.org/pub/source/v12.6/postgresql-12.6.tar.gz
tar -xzvf postgresql-12.6.tar.gz
cd postgresql-12.6
./configure --without-readline
make
make install
export PostgreSQL_ROOT=/usr/local/pgsql
cd ~/indigo
mkdir build
cd build
cmake .. -DBUILD_BINGO_POSTGRES=ON -DBUILD_INDIGO=OFF -DBUILD_INDIGO_WRAPPERS=OFF
cmake --build . --config Release --target package-bingo-postgres -- -j $(nproc)
```
For other OS please find instructions in github actions script
the pull request can be closed

**Comment by byte-for-byte** [comment]
I appreciate all your assistance!
I can confirm that the latest recipe builds successfully.
The remaining issues I had were related to trying to compile against postgresql v13.

**Pull request closed without merging**
